plugins {
    id 'java'
    id 'application'
}

group = 'fnfjava'
version = '1.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation files(
        'gson-2.10.1.jar',
        'json-20231013.jar'
    )
}

application {
    mainClass = 'Main'
}

sourceSets {
    main {
        java {
            srcDirs = ['.', 'Source']
        }
    }
}

tasks.withType(JavaExec).configureEach {
    workingDir = projectDir
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    manifest {
        attributes(
            'Main-Class': 'Main'
        )
    }

    from {
        configurations.runtimeClasspath.collect {
            it.isDirectory() ? it : zipTree(it)
        }
    }
}
